TERMINATION = -1
CREATION = 0
POWERING = 1

HOST_PRIVISIONING = 2

VOLUME_ALLOCATION = 3
VOLUME_ALLOCATOR = 4
VOLUME_DETACH = 5
VOLUME_ATACH = 5

CONTAINER_ALLOCATION = 6
CONTAINER_SCHEDULER = 7
MICROSERVICE_EVALUATION = 8

PROCESS_COMPLETE_CHECK = 8
CORE_CLEAR_INSTRUCTIONS = 9
CORE_EXECUTE_PROCESS = 10
CPU_SCHEDULE_PROCESS = 11

HOST_SCHEDULE_PACKET = 12

REQUEST_SCHEDULER = 13

HOST_EVALUATION = 14

MONITOR_PRIORITY = 15
